# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type_user',
            field=models.CharField(choices=[('US', 'Пользователь'), ('DP', 'Диспетчер')], default='US', max_length=2),
        ),
    ]
