# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_type_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Расположение')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='be',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.BE', verbose_name='Расположение'),
        ),
    ]
