# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160822_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='be',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.BE', verbose_name='Расположение'),
        ),
    ]
