# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 06:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Марка автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='AutoModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Модель автомобиля')),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.AutoMarks')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fedNumber', models.CharField(max_length=50, verbose_name='Гос.номер автомобиля')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False, verbose_name='метка удаления')),
                ('marka_model_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatcher.AutoModels', verbose_name='марка-модель')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за авто')),
            ],
        ),
    ]
