# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160822_1542'),
        ('dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='be',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.BE', verbose_name='Расположение'),
        ),
    ]
